### PR TITLE
Rename _validSignatures to _validSupport

### PR DESCRIPTION
**Pull request by geoknee**

### CODE REVIEW

**Comment by andrewgordstewart** [comment]
>validSupport name suggests that only the supporting states will be validated.

The supported state itself is a part of the support, which might alleviate that confusion

**Comment by kerzhner** [comment]
Thanks @andrewgordstewart. Do you know if the support nomenclature is borrowed from elsewhere? Or something we came up with on our own. I am totally fine with the supported state being part of the support. But, to me, typically the object supported is not part of the support :)

**Comment by andrewgordstewart** [comment]
I think I pretty much made it up on the spot, when trying to come up with a name for it. I think of it this way:
- to know that a state `s` is supported, I need proof that all participants support a recent-enough state `s'` which leads to `s`
- In the case where all participants support the state `s` itself, the proof is `proofOfSupport := { states: [s], signatures: signatures }` where `signatures: Signature[]` has one (valid) signature per participant

You might also say in this situation that `signatures` is the _support_ of the array of states `[s]`, which also seems reasonable. I'm not sure what you'd call the `proof` object in that case.

**Comment by geoknee** [comment]
> Also, to me, validSupport suggests that transitions are will be also validated inside the method call.

This is a good point. Will close until we come up with a more descriptive naming scheme for the various checks that are performed, potentially combining `_validSignatures` with `_validTransitionChain`.

**Comment by geoknee** [comment]
See #91

**Pull request closed without merging**
