### PR TITLE
Move contract tests to contract folder

### PR DESCRIPTION
**Pull request by lalexgap**
Move all the contract tests to their own folder to keep it separate from other tests.

### CODE REVIEW

**Comment by lalexgap** [comment]
> Do you think that directory structure `test/contract-tests` has redundant naming? What about something like `test/contract`?

That's what I originally named it, but I was hoping to mirror the `src` directory structure in `test`. So that means `test/contract` will contain tests for `src/contract` and we need a separate directory for contract tests.

**Comment by kerzhner** [comment]
Gotcha. Does that mean the directory structure will be:
```
test
- contract-tests
- contract
```
I think that might be a bit confusing.

I guess our other options are:
- tests for solidity contracts are in the `contracts` directory.
- `test` directory contains `contracts` and `src` directories.

**Comment by andrewgordstewart** [comment]
> > Do you think that directory structure `test/contract-tests` has redundant naming? What about something like `test/contract`?
> 
> That's what I originally named it, but I was hoping to mirror the `src` directory structure in `test`. So that means `test/contract` will contain tests for `src/contract` and we need a separate directory for contract tests.

What are contract tests in this context?

**Comment by lalexgap** [comment]
> Gotcha. Does that mean the directory structure will be:
> 
> ```
> test
> - contract-tests
> - contract
> ```
> 
> I think that might be a bit confusing.
> 
> I guess our other options are:
> 
> * tests for solidity contracts are in the `contracts` directory.
> * `test` directory contains `contracts` and `src` directories.

Yeah a `src` folder in `test` might be the clearest. I'll do that in a separate PR to avoid renaming eadaches.

**Pull request merged**
